import { BellOutlined, EditOutlined, LogoutOutlined, SafetyOutlined } from '@ant-design/icons'
import { Avatar, Button, Empty, Form, Input, Modal, Switch, Tabs, message } from 'antd'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../store/AppStore'
import { WorkCard } from '../features/inspiration'
import { useState } from 'react'
import type { Work } from '../types'
import { WorkDetail } from '../features/inspiration'

export function ProfilePage(){
 const {user,works,logout}=useApp(),nav=useNavigate(),[active,setActive]=useState<Work|null>(null),[editOpen,setEditOpen]=useState(false),[settings,setSettings]=useState<'notice'|'security'|null>(null),[msg,ctx]=message.useMessage()
 if(!user)return <main className="page">{ctx}<div className="surface py-24"><Empty description="登录后查看个人主页"><Button type="primary" onClick={()=>nav('/')}>返回首页登录</Button></Empty></div></main>
 const settingContent=settings==='notice'?<div className="grid gap-4"><div className="flex justify-between"><span>生成完成通知</span><Switch defaultChecked/></div><div className="flex justify-between"><span>活动与模型更新</span><Switch defaultChecked/></div><div className="flex justify-between"><span>社区互动通知</span><Switch/></div></div>:<div className="grid gap-3"><Button block className="!h-12 !justify-start">绑定手机：138****2026</Button><Button block className="!h-12 !justify-start">修改登录密码</Button><Button block className="!h-12 !justify-start">登录设备管理</Button></div>
 return <main className="page">{ctx}<section className="surface flex items-center gap-5 p-6 max-[600px]:items-start"><Avatar size={76} src={user.avatar}/><div className="flex-1"><h1 className="mb-1 mt-0 text-xl">{user.name}</h1><span className="text-[#54d6cf]">{user.level}</span><div className="mt-3 flex gap-6 text-[#929bad]"><span><b className="text-white">{works.length}</b> 作品</span><span><b className="text-white">{user.following}</b> 关注</span><span><b className="text-white">{user.followers}</b> 粉丝</span></div></div><Button icon={<EditOutlined/>} onClick={()=>setEditOpen(true)}>编辑资料</Button></section><Tabs className="mt-5" items={[{key:'works',label:'我的作品',children:<div className="masonry">{works.slice(0,6).map(w=><WorkCard key={w.id} work={w} onOpen={setActive}/>)}</div>},{key:'settings',label:'账户设置',children:<div className="surface divide-y divide-[#252b38]"><Button block type="text" className="!h-14 !justify-start" icon={<BellOutlined/>} onClick={()=>setSettings('notice')}>消息与通知设置</Button><Button block type="text" className="!h-14 !justify-start" icon={<SafetyOutlined/>} onClick={()=>setSettings('security')}>账号与安全</Button><Button danger block type="text" className="!h-14 !justify-start" icon={<LogoutOutlined/>} onClick={()=>{logout();nav('/')}}>退出登录</Button></div>} ]}/>
 <WorkDetail work={active} onClose={()=>setActive(null)}/><Modal title="编辑个人资料" open={editOpen} footer={null} onCancel={()=>setEditOpen(false)}><Form layout="vertical" initialValues={{name:user.name,bio:'用 AI 记录每一个灵感瞬间'}} onFinish={()=>{setEditOpen(false);msg.success('个人资料已保存')}}><Form.Item label="头像"><Avatar size={64} src={user.avatar}/><Button type="link">更换头像</Button></Form.Item><Form.Item name="name" label="昵称"><Input/></Form.Item><Form.Item name="bio" label="个人简介"><Input.TextArea rows={3}/></Form.Item><Button block type="primary" htmlType="submit">保存修改</Button></Form></Modal><Modal title={settings==='notice'?'消息与通知设置':'账号与安全'} open={!!settings} onCancel={()=>setSettings(null)} onOk={()=>{setSettings(null);msg.success('设置已保存')}}>{settingContent}</Modal></main>
}
