import { BellOutlined, DeleteOutlined, EditOutlined, LogoutOutlined, SafetyOutlined } from '@ant-design/icons'
import { Avatar, Button, Empty, Form, Input, List, Modal, Switch, Tabs, message } from 'antd'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../store/AppStore'
import { WorkCard, WorkDetail } from '../features/inspiration'
import { useEffect, useState } from 'react'
import type { UserSession, Work } from '../types'
import { apiClient } from '../utils/api'

type SecurityModal = 'phone' | 'password' | 'sessions' | null

const maskPhone = (phone?: string) => phone ? `${phone.slice(0, 3)}****${phone.slice(-4)}` : '未绑定'

export function ProfilePage(){
 const {user,logout,refreshProfile}=useApp(),nav=useNavigate(),[active,setActive]=useState<Work|null>(null),[myWorks,setMyWorks]=useState<Work[]>([]),[myWorksTotal,setMyWorksTotal]=useState(0),[worksLoading,setWorksLoading]=useState(false),[editOpen,setEditOpen]=useState(false),[settings,setSettings]=useState<'notice'|'security'|null>(null),[securityOpen,setSecurityOpen]=useState<SecurityModal>(null),[sessions,setSessions]=useState<UserSession[]>([]),[sending,setSending]=useState(false),[msg,ctx]=message.useMessage()
 useEffect(()=>{if(!user){setMyWorks([]);setMyWorksTotal(0);return}setWorksLoading(true);void apiClient.works.mine({page:1,page_size:100}).then(result=>{setMyWorks(result.list);setMyWorksTotal(result.total)}).catch(error=>{console.error('加载我的作品失败:',error);msg.error(error instanceof Error?error.message:'加载我的作品失败')}).finally(()=>setWorksLoading(false))},[msg,user?.id])
 if(!user)return <main className="page">{ctx}<div className="surface py-24"><Empty description="登录后查看个人主页"><Button type="primary" onClick={()=>nav('/')}>返回首页登录</Button></Empty></div></main>
 const sendPhoneVerification=async()=>{setSending(true);try{await apiClient.auth.sendCode({email:user.email,type:'reset'});msg.success('验证码已发送至当前账号邮箱')}catch(error){msg.error(error instanceof Error?error.message:'发送失败')}finally{setSending(false)}}
 const openSessions=async()=>{try{setSessions(await apiClient.user.listSessions());setSecurityOpen('sessions')}catch(error){msg.error(error instanceof Error?error.message:'加载设备失败')}}
 const revokeSession=async(id:string)=>{try{await apiClient.user.revokeSession(id);setSessions(items=>items.filter(item=>item.id!==id));msg.success('设备已退出登录')}catch(error){msg.error(error instanceof Error?error.message:'操作失败')}}
 const securityContent=<div className="grid gap-3"><Button block className="!h-12 !justify-start" onClick={()=>setSecurityOpen('phone')}>绑定手机：{maskPhone(user.phone)}</Button><Button block className="!h-12 !justify-start" onClick={()=>setSecurityOpen('password')}>修改登录密码</Button><Button block className="!h-12 !justify-start" onClick={openSessions}>登录设备管理</Button></div>
 return <main className="page">{ctx}<section className="surface flex items-center gap-5 p-6 max-[600px]:items-start"><Avatar size={76} src={user.avatar}/><div className="flex-1"><h1 className="mb-1 mt-0 text-xl">{user.name}</h1><span className="text-[#54d6cf]">{user.level}</span><div className="profile-stats mt-3 flex gap-6"><span><b>{myWorksTotal}</b> 作品</span><span><b>{user.following}</b> 关注</span><span><b>{user.followers}</b> 粉丝</span></div></div><Button icon={<EditOutlined/>} onClick={()=>setEditOpen(true)}>编辑资料</Button></section><Tabs className="mt-5" items={[{key:'works',label:'我的作品',children:worksLoading?<div className="surface py-20 text-center text-[#929bad]">加载作品中...</div>:myWorks.length?<div className="masonry">{myWorks.map(w=><WorkCard key={w.id} work={w} onOpen={setActive}/>)}</div>:<div className="surface py-20"><Empty description="还没有发布作品"><Button type="primary" onClick={()=>nav('/create')}>开始创作</Button></Empty></div>},{key:'settings',label:'账户设置',children:<div className="surface profile-settings"><Button block type="text" className="!h-14 !justify-start" icon={<BellOutlined/>} onClick={()=>setSettings('notice')}>消息与通知设置</Button><Button block type="text" className="!h-14 !justify-start" icon={<SafetyOutlined/>} onClick={()=>setSettings('security')}>账号与安全</Button><Button danger block type="text" className="!h-14 !justify-start" icon={<LogoutOutlined/>} onClick={()=>{logout();nav('/')}}>退出登录</Button></div>} ]}/>
 <WorkDetail work={active} onClose={()=>setActive(null)}/>
 <Modal title="编辑个人资料" open={editOpen} footer={null} onCancel={()=>setEditOpen(false)} destroyOnHidden><Form layout="vertical" initialValues={{name:user.name,bio:user.bio}} onFinish={async values=>{try{await apiClient.user.updateProfile(values);await refreshProfile();setEditOpen(false);msg.success('个人资料已保存')}catch(error){msg.error(error instanceof Error?error.message:'保存失败')}}}><Form.Item name="name" label="昵称" rules={[{required:true,message:'请输入昵称'}]}><Input maxLength={50}/></Form.Item><Form.Item name="bio" label="个人简介"><Input.TextArea rows={3} maxLength={500}/></Form.Item><Button block type="primary" htmlType="submit">保存修改</Button></Form></Modal>
 <Modal title={settings==='notice'?'消息与通知设置':'账号与安全'} open={!!settings} footer={settings==='notice'?undefined:null} onCancel={()=>setSettings(null)} onOk={()=>{setSettings(null);msg.success('设置已保存')}}>{settings==='notice'?<div className="grid gap-4"><div className="flex justify-between"><span>生成完成通知</span><Switch defaultChecked/></div><div className="flex justify-between"><span>活动与模型更新</span><Switch defaultChecked/></div><div className="flex justify-between"><span>社区互动通知</span><Switch/></div></div>:securityContent}</Modal>
 <Modal title="绑定手机" open={securityOpen==='phone'} footer={null} onCancel={()=>setSecurityOpen(null)} destroyOnHidden><p className="mb-5 text-[#929bad]">为保护账号安全，验证码将发送到当前账号邮箱。</p><Form layout="vertical" onFinish={async values=>{try{await apiClient.user.bindPhone(values);await refreshProfile();setSecurityOpen(null);msg.success('手机号绑定成功')}catch(error){msg.error(error instanceof Error?error.message:'绑定失败')}}}><Form.Item label="手机号" name="phone" rules={[{required:true,message:'请输入手机号'},{pattern:/^\+?[1-9]\d{7,14}$/,message:'请输入国际格式手机号'}]}><Input placeholder="例如 +8613812345678"/></Form.Item><Form.Item label="邮箱验证码" name="code" rules={[{required:true,message:'请输入验证码'},{len:6,message:'请输入 6 位验证码'}]}><Input maxLength={6} suffix={<Button type="link" size="small" loading={sending} onClick={sendPhoneVerification}>获取验证码</Button>}/></Form.Item><Button type="primary" block htmlType="submit">确认绑定</Button></Form></Modal>
 <Modal title="修改登录密码" open={securityOpen==='password'} footer={null} onCancel={()=>setSecurityOpen(null)} destroyOnHidden><Form layout="vertical" onFinish={async values=>{try{await apiClient.user.changePassword({current_password:values.current_password,new_password:values.new_password});setSecurityOpen(null);msg.success('密码已修改，其他设备已退出登录')}catch(error){msg.error(error instanceof Error?error.message:'修改失败')}}}><Form.Item label="当前密码" name="current_password" rules={[{required:true,message:'请输入当前密码'}]}><Input.Password autoComplete="current-password"/></Form.Item><Form.Item label="新密码" name="new_password" rules={[{required:true,message:'请输入新密码'},{min:8,message:'密码至少 8 位'}]}><Input.Password autoComplete="new-password"/></Form.Item><Form.Item label="确认新密码" name="confirm_new_password" dependencies={['new_password']} rules={[{required:true,message:'请再次输入新密码'},({getFieldValue})=>({validator(_,value){return !value||getFieldValue('new_password')===value?Promise.resolve():Promise.reject(new Error('两次输入的新密码不一致'))}})]}><Input.Password autoComplete="new-password"/></Form.Item><Button type="primary" block htmlType="submit">确认修改</Button></Form></Modal>
 <Modal title="登录设备管理" open={securityOpen==='sessions'} footer={null} onCancel={()=>setSecurityOpen(null)}><List dataSource={sessions} locale={{emptyText:'没有活跃设备'}} renderItem={item=><List.Item actions={item.current?[]:[<Button key="revoke" danger type="text" icon={<DeleteOutlined/>} onClick={()=>revokeSession(item.id)}>退出</Button>]}><List.Item.Meta title={item.current?`${item.device}（当前设备）`:item.device} description={`${item.ip || '未知 IP'} · 登录于 ${item.created_at}`}/></List.Item>}/></Modal>
 </main>
}
