import { CheckOutlined, CustomerServiceOutlined, TeamOutlined } from '@ant-design/icons'
import { Button, Modal, Segmented, message } from 'antd'
import { useState } from 'react'

export function CommunityDialog({open,onClose}:{open:boolean;onClose:()=>void}){
 const [type,setType]=useState('微信社群'),[backupOpen,setBackupOpen]=useState(false),[msg,ctx]=message.useMessage()
 const copyQQGroup=async()=>{try{await navigator.clipboard.writeText('1085400229');msg.success('QQ 群号已复制')}catch{msg.info('QQ 群号：1085400229')}
 }
 return <>{ctx}<Modal title="加入潮汐创作者社群" open={open} footer={null} onCancel={onClose}><Segmented block options={['微信社群','QQ 社群','创作者社区']} value={type} onChange={v=>setType(String(v))}/>{type==='微信社群'?<div className="community-panel community-wechat"><img src="/community/wechat-group-5.png" alt="CodeX 中文网 5 群微信社群二维码"/><p>获取模型资讯、创作技巧、活动奖励和问题答疑。</p><div className="community-benefits"><span><CheckOutlined/> 新模型内测</span><span><CheckOutlined/> 每周创作挑战</span><span><CheckOutlined/> 专属问题答疑</span></div><div className="community-expiry-notice"><span>群二维码可能会过期</span><Button type="link" size="small" onClick={()=>setBackupOpen(true)}>二维码失效？点这里</Button></div><small>请使用微信扫描二维码加入社群。</small></div>:type==='QQ 社群'?<div className="community-panel community-qq"><img src="/community/qq-group.png" alt="CodeX 中文网 QQ 社群二维码"/><p>获取模型资讯、创作技巧、活动奖励和问题答疑。</p><div className="community-benefits"><span><CheckOutlined/> 新模型内测</span><span><CheckOutlined/> 每周创作挑战</span><span><CheckOutlined/> 专属问题答疑</span></div><Button type="primary" href="https://qm.qq.com/q/FSroSw8awo" target="_blank" rel="noreferrer">打开 QQ 群</Button><div className="community-qq-number"><span>QQ群号：1085400229</span><Button type="link" size="small" onClick={()=>void copyQQGroup()}>复制群号</Button></div><small>请使用 QQ 扫描二维码加入社群。</small></div>:<div className="community-panel"><div className="community-mark"><TeamOutlined/></div><h3>{type}</h3><p>交流提示词、工作流与模型体验，参与每周创作挑战。</p><div className="community-benefits"><span><CheckOutlined/> 新模型内测</span><span><CheckOutlined/> 每周创作挑战</span><span><CheckOutlined/> 专属问题答疑</span></div><Button type="primary" icon={<CustomerServiceOutlined/>} onClick={()=>msg.success(`${type}加入信息已复制`)}>获取加入方式</Button></div>}</Modal><Modal title="备用社群二维码" open={backupOpen} footer={null} onCancel={()=>setBackupOpen(false)}><div className="community-panel community-backup"><img src="/community/wechat-community-backup.png" alt="CodeX 中文网社群备用二维码"/><p>请使用微信扫描二维码加入社群。</p></div></Modal></>
}
