CREATE DATABASE IF NOT EXISTS `agi_platform`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE `agi_platform`;

CREATE TABLE `users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(191) NULL,
  `phone` VARCHAR(32) NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(64) NOT NULL DEFAULT '',
  `avatar_url` VARCHAR(500) NOT NULL DEFAULT '',
  `credits` BIGINT NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `last_login_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_email` (`email`),
  UNIQUE KEY `uk_users_phone` (`phone`),
  KEY `idx_users_status` (`status`),
  KEY `idx_users_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `admin_users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(64) NOT NULL DEFAULT '',
  `role` VARCHAR(32) NOT NULL DEFAULT 'admin',
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `last_login_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_admin_users_username` (`username`),
  KEY `idx_admin_users_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `api_keys` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL DEFAULT '',
  `key_prefix` VARCHAR(32) NOT NULL,
  `key_hash` VARCHAR(255) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `last_used_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_api_keys_hash` (`key_hash`),
  KEY `idx_api_keys_user_id` (`user_id`),
  KEY `idx_api_keys_key_prefix` (`key_prefix`),
  CONSTRAINT `fk_api_keys_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `wallet_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `type` VARCHAR(32) NOT NULL,
  `amount` BIGINT NOT NULL,
  `balance_before` BIGINT NOT NULL,
  `balance_after` BIGINT NOT NULL,
  `related_type` VARCHAR(32) NOT NULL DEFAULT '',
  `related_id` BIGINT UNSIGNED NULL,
  `remark` VARCHAR(500) NOT NULL DEFAULT '',
  `operator_type` VARCHAR(32) NOT NULL DEFAULT 'system',
  `operator_id` BIGINT UNSIGNED NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_wallet_logs_user_id` (`user_id`),
  KEY `idx_wallet_logs_type` (`type`),
  KEY `idx_wallet_logs_related` (`related_type`, `related_id`),
  KEY `idx_wallet_logs_created_at` (`created_at`),
  CONSTRAINT `fk_wallet_logs_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `providers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `base_url` VARCHAR(500) NOT NULL DEFAULT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `timeout_seconds` INT NOT NULL DEFAULT 60,
  `retry_count` INT NOT NULL DEFAULT 1,
  `priority` INT NOT NULL DEFAULT 100,
  `daily_limit` BIGINT NULL,
  `remark` VARCHAR(500) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_providers_code` (`code`),
  KEY `idx_providers_type` (`type`),
  KEY `idx_providers_enabled_priority` (`enabled`, `priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `provider_keys` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `provider_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL DEFAULT '',
  `api_key_encrypted` TEXT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `weight` INT NOT NULL DEFAULT 100,
  `daily_limit` BIGINT NULL,
  `daily_used` BIGINT NOT NULL DEFAULT 0,
  `last_used_at` DATETIME NULL,
  `last_error` VARCHAR(1000) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_provider_keys_provider_id` (`provider_id`),
  KEY `idx_provider_keys_status_weight` (`status`, `weight`),
  CONSTRAINT `fk_provider_keys_provider_id` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `image_models` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `display_name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(500) NOT NULL DEFAULT '',
  `cover_url` VARCHAR(500) NOT NULL DEFAULT '',
  `price_credits` BIGINT NOT NULL DEFAULT 0,
  `supported_sizes` JSON NOT NULL,
  `support_text_to_image` TINYINT(1) NOT NULL DEFAULT 1,
  `support_image_to_image` TINYINT(1) NOT NULL DEFAULT 0,
  `support_edit` TINYINT(1) NOT NULL DEFAULT 0,
  `max_images_per_request` INT NOT NULL DEFAULT 1,
  `auto_refund_on_failure` TINYINT(1) NOT NULL DEFAULT 1,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `recommended` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 100,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_image_models_code` (`code`),
  KEY `idx_image_models_enabled_sort` (`enabled`, `sort_order`),
  KEY `idx_image_models_recommended` (`recommended`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `image_model_routes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model_id` BIGINT UNSIGNED NOT NULL,
  `provider_id` BIGINT UNSIGNED NOT NULL,
  `provider_key_id` BIGINT UNSIGNED NULL,
  `provider_model_name` VARCHAR(191) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `priority` INT NOT NULL DEFAULT 100,
  `weight` INT NOT NULL DEFAULT 100,
  `extra_config` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_image_model_routes_model_id` (`model_id`),
  KEY `idx_image_model_routes_provider_id` (`provider_id`),
  KEY `idx_image_model_routes_provider_key_id` (`provider_key_id`),
  KEY `idx_image_model_routes_enabled_priority` (`enabled`, `priority`),
  CONSTRAINT `fk_image_model_routes_model_id` FOREIGN KEY (`model_id`) REFERENCES `image_models` (`id`),
  CONSTRAINT `fk_image_model_routes_provider_id` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`),
  CONSTRAINT `fk_image_model_routes_provider_key_id` FOREIGN KEY (`provider_key_id`) REFERENCES `provider_keys` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `image_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `api_key_id` BIGINT UNSIGNED NULL,
  `model_id` BIGINT UNSIGNED NOT NULL,
  `route_id` BIGINT UNSIGNED NULL,
  `provider_id` BIGINT UNSIGNED NULL,
  `provider_key_id` BIGINT UNSIGNED NULL,
  `source` VARCHAR(32) NOT NULL DEFAULT 'web',
  `prompt` TEXT NOT NULL,
  `negative_prompt` TEXT NULL,
  `size` VARCHAR(32) NOT NULL,
  `num_images` INT NOT NULL DEFAULT 1,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `progress` INT NOT NULL DEFAULT 0,
  `credits_used` BIGINT NOT NULL DEFAULT 0,
  `refund_status` VARCHAR(32) NOT NULL DEFAULT 'none',
  `provider_request_id` VARCHAR(191) NOT NULL DEFAULT '',
  `provider_response` JSON NULL,
  `error_code` VARCHAR(64) NOT NULL DEFAULT '',
  `error_message` VARCHAR(1000) NOT NULL DEFAULT '',
  `started_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_image_tasks_task_no` (`task_no`),
  KEY `idx_image_tasks_user_id` (`user_id`),
  KEY `idx_image_tasks_status_created_at` (`status`, `created_at`),
  KEY `idx_image_tasks_model_id` (`model_id`),
  KEY `idx_image_tasks_provider_id` (`provider_id`),
  KEY `idx_image_tasks_api_key_id` (`api_key_id`),
  CONSTRAINT `fk_image_tasks_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_image_tasks_api_key_id` FOREIGN KEY (`api_key_id`) REFERENCES `api_keys` (`id`),
  CONSTRAINT `fk_image_tasks_model_id` FOREIGN KEY (`model_id`) REFERENCES `image_models` (`id`),
  CONSTRAINT `fk_image_tasks_route_id` FOREIGN KEY (`route_id`) REFERENCES `image_model_routes` (`id`),
  CONSTRAINT `fk_image_tasks_provider_id` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`),
  CONSTRAINT `fk_image_tasks_provider_key_id` FOREIGN KEY (`provider_key_id`) REFERENCES `provider_keys` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `image_assets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `model_id` BIGINT UNSIGNED NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `storage_provider` VARCHAR(64) NOT NULL DEFAULT '',
  `storage_bucket` VARCHAR(191) NOT NULL DEFAULT '',
  `storage_key` VARCHAR(500) NOT NULL DEFAULT '',
  `width` INT NULL,
  `height` INT NULL,
  `mime_type` VARCHAR(64) NOT NULL DEFAULT 'image/png',
  `size_bytes` BIGINT NULL,
  `prompt` TEXT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `is_public` TINYINT(1) NOT NULL DEFAULT 0,
  `download_count` BIGINT NOT NULL DEFAULT 0,
  `violation_status` VARCHAR(32) NOT NULL DEFAULT 'normal',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_image_assets_task_id` (`task_id`),
  KEY `idx_image_assets_user_id_created_at` (`user_id`, `created_at`),
  KEY `idx_image_assets_model_id` (`model_id`),
  KEY `idx_image_assets_status` (`status`),
  CONSTRAINT `fk_image_assets_task_id` FOREIGN KEY (`task_id`) REFERENCES `image_tasks` (`id`),
  CONSTRAINT `fk_image_assets_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_image_assets_model_id` FOREIGN KEY (`model_id`) REFERENCES `image_models` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `video_models` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `display_name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(500) NOT NULL DEFAULT '',
  `price_credits` BIGINT NOT NULL DEFAULT 0,
  `supported_aspect_ratios` JSON NOT NULL,
  `supported_seconds` JSON NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `recommended` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 100,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_video_models_code` (`code`),
  KEY `idx_video_models_enabled_sort` (`enabled`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `video_model_routes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model_id` BIGINT UNSIGNED NOT NULL,
  `provider_id` BIGINT UNSIGNED NOT NULL,
  `provider_key_id` BIGINT UNSIGNED NULL,
  `provider_model_name` VARCHAR(191) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `priority` INT NOT NULL DEFAULT 100,
  `weight` INT NOT NULL DEFAULT 100,
  `extra_config` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_video_model_routes_model_id` (`model_id`),
  KEY `idx_video_model_routes_provider_id` (`provider_id`),
  KEY `idx_video_model_routes_provider_key_id` (`provider_key_id`),
  KEY `idx_video_model_routes_enabled_priority` (`enabled`, `priority`),
  CONSTRAINT `fk_video_model_routes_model_id` FOREIGN KEY (`model_id`) REFERENCES `video_models` (`id`),
  CONSTRAINT `fk_video_model_routes_provider_id` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`),
  CONSTRAINT `fk_video_model_routes_provider_key_id` FOREIGN KEY (`provider_key_id`) REFERENCES `provider_keys` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `video_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `api_key_id` BIGINT UNSIGNED NULL,
  `model_id` BIGINT UNSIGNED NOT NULL,
  `route_id` BIGINT UNSIGNED NULL,
  `provider_id` BIGINT UNSIGNED NULL,
  `provider_key_id` BIGINT UNSIGNED NULL,
  `source` VARCHAR(32) NOT NULL DEFAULT 'web',
  `prompt` TEXT NOT NULL,
  `seconds` INT NOT NULL DEFAULT 15,
  `aspect_ratio` VARCHAR(32) NOT NULL DEFAULT '9:16',
  `images` JSON NULL,
  `videos` JSON NULL,
  `audios` JSON NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `progress` INT NOT NULL DEFAULT 0,
  `credits_used` BIGINT NOT NULL DEFAULT 0,
  `refund_status` VARCHAR(32) NOT NULL DEFAULT 'none',
  `provider_task_id` VARCHAR(191) NOT NULL DEFAULT '',
  `provider_response` JSON NULL,
  `error_message` VARCHAR(1000) NOT NULL DEFAULT '',
  `started_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_video_tasks_task_no` (`task_no`),
  KEY `idx_video_tasks_user_id` (`user_id`),
  KEY `idx_video_tasks_status_created_at` (`status`, `created_at`),
  KEY `idx_video_tasks_model_id` (`model_id`),
  KEY `idx_video_tasks_provider_id` (`provider_id`),
  CONSTRAINT `fk_video_tasks_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_video_tasks_api_key_id` FOREIGN KEY (`api_key_id`) REFERENCES `api_keys` (`id`),
  CONSTRAINT `fk_video_tasks_model_id` FOREIGN KEY (`model_id`) REFERENCES `video_models` (`id`),
  CONSTRAINT `fk_video_tasks_route_id` FOREIGN KEY (`route_id`) REFERENCES `video_model_routes` (`id`),
  CONSTRAINT `fk_video_tasks_provider_id` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`),
  CONSTRAINT `fk_video_tasks_provider_key_id` FOREIGN KEY (`provider_key_id`) REFERENCES `provider_keys` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `video_assets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `model_id` BIGINT UNSIGNED NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `storage_provider` VARCHAR(64) NOT NULL DEFAULT '',
  `storage_bucket` VARCHAR(191) NOT NULL DEFAULT '',
  `storage_key` VARCHAR(500) NOT NULL DEFAULT '',
  `mime_type` VARCHAR(64) NOT NULL DEFAULT 'video/mp4',
  `size_bytes` BIGINT NULL,
  `duration_seconds` INT NULL,
  `prompt` TEXT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `is_public` TINYINT(1) NOT NULL DEFAULT 0,
  `download_count` BIGINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_video_assets_task_id` (`task_id`),
  KEY `idx_video_assets_user_id_created_at` (`user_id`, `created_at`),
  KEY `idx_video_assets_model_id` (`model_id`),
  KEY `idx_video_assets_status` (`status`),
  CONSTRAINT `fk_video_assets_task_id` FOREIGN KEY (`task_id`) REFERENCES `video_tasks` (`id`),
  CONSTRAINT `fk_video_assets_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_video_assets_model_id` FOREIGN KEY (`model_id`) REFERENCES `video_models` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `credit_packages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `credits` BIGINT NOT NULL,
  `bonus_credits` BIGINT NOT NULL DEFAULT 0,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `sort_order` INT NOT NULL DEFAULT 100,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_credit_packages_enabled_sort` (`enabled`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `package_id` BIGINT UNSIGNED NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `credits` BIGINT NOT NULL,
  `payment_channel` VARCHAR(64) NOT NULL DEFAULT '',
  `payment_trade_no` VARCHAR(191) NOT NULL DEFAULT '',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `paid_at` DATETIME NULL,
  `remark` VARCHAR(500) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_orders_order_no` (`order_no`),
  KEY `idx_orders_user_id` (`user_id`),
  KEY `idx_orders_status_created_at` (`status`, `created_at`),
  KEY `idx_orders_payment_trade_no` (`payment_trade_no`),
  CONSTRAINT `fk_orders_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_orders_package_id` FOREIGN KEY (`package_id`) REFERENCES `credit_packages` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_callbacks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT UNSIGNED NULL,
  `order_no` VARCHAR(64) NOT NULL DEFAULT '',
  `payment_channel` VARCHAR(64) NOT NULL DEFAULT '',
  `event_type` VARCHAR(64) NOT NULL DEFAULT '',
  `payload` JSON NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'received',
  `error_message` VARCHAR(1000) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_payment_callbacks_order_id` (`order_id`),
  KEY `idx_payment_callbacks_order_no` (`order_no`),
  KEY `idx_payment_callbacks_created_at` (`created_at`),
  CONSTRAINT `fk_payment_callbacks_order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `api_request_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NULL,
  `api_key_id` BIGINT UNSIGNED NULL,
  `request_id` VARCHAR(64) NOT NULL,
  `method` VARCHAR(16) NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `status_code` INT NOT NULL DEFAULT 0,
  `credits_used` BIGINT NOT NULL DEFAULT 0,
  `ip` VARCHAR(64) NOT NULL DEFAULT '',
  `user_agent` VARCHAR(500) NOT NULL DEFAULT '',
  `error_message` VARCHAR(1000) NOT NULL DEFAULT '',
  `latency_ms` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_api_request_logs_request_id` (`request_id`),
  KEY `idx_api_request_logs_user_id` (`user_id`),
  KEY `idx_api_request_logs_api_key_id` (`api_key_id`),
  KEY `idx_api_request_logs_created_at` (`created_at`),
  CONSTRAINT `fk_api_request_logs_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_api_request_logs_api_key_id` FOREIGN KEY (`api_key_id`) REFERENCES `api_keys` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `system_settings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `setting_key` VARCHAR(128) NOT NULL,
  `setting_value` JSON NULL,
  `description` VARCHAR(500) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_system_settings_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `admin_operation_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_id` BIGINT UNSIGNED NULL,
  `action` VARCHAR(128) NOT NULL,
  `target_type` VARCHAR(64) NOT NULL DEFAULT '',
  `target_id` BIGINT UNSIGNED NULL,
  `detail` JSON NULL,
  `ip` VARCHAR(64) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_admin_operation_logs_admin_id` (`admin_id`),
  KEY `idx_admin_operation_logs_target` (`target_type`, `target_id`),
  KEY `idx_admin_operation_logs_created_at` (`created_at`),
  CONSTRAINT `fk_admin_operation_logs_admin_id` FOREIGN KEY (`admin_id`) REFERENCES `admin_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
