<template>
  <div class="accounts-page" v-loading="loading">
    <div class="page-head"><div><h2>账号管理</h2><p>统一管理 AI 供应商账号和模型能力</p></div><el-button type="primary" @click="openAccount()">添加供应商账号</el-button></div>
    <el-row :gutter="16" class="account-grid">
      <el-col v-for="account in accounts" :key="account.id" :xs="24" :sm="12" :lg="8">
        <el-card shadow="never"><template #header><div class="card-head"><strong>{{ account.name }}</strong><el-tag :type="account.is_active?'success':'info'">{{ account.is_active?'启用':'停用' }}</el-tag></div></template><el-descriptions :column="1" size="small"><el-descriptions-item label="供应商">{{ account.provider }}</el-descriptions-item><el-descriptions-item label="接口地址">{{ account.api_url }}</el-descriptions-item><el-descriptions-item label="关联模型">{{ models.filter(m=>m.provider_account_id===account.id).length }}</el-descriptions-item></el-descriptions><div class="card-actions"><el-button size="small" @click="openAccount(account)">编辑</el-button><el-button size="small" type="danger" plain @click="removeAccount(account)">删除</el-button></div></el-card>
      </el-col>
    </el-row>

    <section class="model-section"><div class="section-head"><h3>模型能力</h3><span>图片：比例、清晰度；视频：比例、清晰度、时长、声音</span></div><el-table :data="models"><el-table-column prop="display_name" label="模型"/><el-table-column label="类型" width="90"><template #default="{row}"><el-tag>{{ row.type==='image'?'图片':'视频' }}</el-tag></template></el-table-column><el-table-column label="供应商账号"><template #default="{row}">{{ accountName(row.provider_account_id) }}</template></el-table-column><el-table-column prop="cost" label="基础积分" width="100"/><el-table-column label="状态" width="90"><template #default="{row}"><el-switch v-model="row.is_active" @change="toggleModel(row)"/></template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button size="small" @click="openModel(row)">配置</el-button></template></el-table-column></el-table></section>

    <el-dialog v-model="accountDialog" :title="accountForm.id?'编辑供应商账号':'添加供应商账号'" width="600px"><el-form :model="accountForm" label-width="100px"><el-form-item label="账号名称"><el-input v-model="accountForm.name"/></el-form-item><el-form-item label="供应商"><el-select v-model="accountForm.provider" class="full"><el-option v-for="item in providers" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item><el-form-item label="API 地址"><el-input v-model="accountForm.api_url"/></el-form-item><el-form-item label="API Key"><el-input v-model="accountForm.api_key" type="password" show-password :placeholder="accountForm.id?'留空表示不修改':'请输入 API Key'"/></el-form-item><el-form-item label="启用"><el-switch v-model="accountForm.is_active"/></el-form-item></el-form><template #footer><el-button @click="accountDialog=false">取消</el-button><el-button type="primary" @click="saveAccount">保存</el-button></template></el-dialog>

    <el-dialog v-model="modelDialog" title="配置模型能力" width="680px"><el-form :model="modelForm" label-width="110px"><el-form-item label="模型名称"><el-input v-model="modelForm.display_name"/></el-form-item><el-form-item label="供应商账号"><el-select v-model="modelForm.provider_account_id" class="full"><el-option v-for="item in compatibleAccounts" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="基础积分"><el-input-number v-model="modelForm.cost" :min="0"/></el-form-item><el-form-item label="描述"><el-input v-model="modelForm.description" type="textarea"/></el-form-item><el-divider>支持能力</el-divider><el-form-item label="画面比例"><el-input v-model="modelForm.ratio" placeholder="1:1,16:9,9:16"/></el-form-item><el-form-item label="清晰度"><el-input v-model="modelForm.resolution" placeholder="1K,2K|2 或 720P,1080P|6"/></el-form-item><template v-if="modelForm.type==='video'"><el-form-item label="视频时长"><el-input v-model="modelForm.duration" placeholder="5s,10s|12"/></el-form-item><el-form-item label="支持声音"><el-switch v-model="modelForm.sound_enabled"/><span class="hint">开启后用户端显示声音开关</span></el-form-item><el-form-item v-if="modelForm.sound_enabled" label="默认声音"><el-switch v-model="modelForm.sound_default"/></el-form-item></template></el-form><template #footer><el-button @click="modelDialog=false">取消</el-button><el-button type="primary" @click="saveModel">保存</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import request from '@/utils/request'
const loading=ref(false),accounts=ref([]),models=ref([]),accountDialog=ref(false),modelDialog=ref(false)
const providers=[{label:'OpenAI',value:'openai'},{label:'即梦',value:'jimeng'},{label:'Wave',value:'wave'},{label:'演示',value:'demo'}]
const emptyAccount=()=>({id:0,name:'',provider:'openai',api_url:'',api_key:'',is_active:true,extra_config:{}})
const accountForm=reactive(emptyAccount())
const modelForm=reactive({id:0,type:'image',provider:'',display_name:'',provider_account_id:null,cost:0,description:'',ratio:'',resolution:'',duration:'',sound_enabled:false,sound_default:false})
const compatibleAccounts=computed(()=>accounts.value.filter(item=>item.provider===modelForm.provider&&item.is_active))
const accountName=id=>accounts.value.find(item=>item.id===id)?.name||'未关联'
const optionText=config=>(config?.options||[]).map(item=>`${item.value}${item.extra_cost?`|${item.extra_cost}`:''}`).join(',')
const makeSelect=(label,text)=>{const options=text.split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const [value,extra]=x.split('|');const item={value,label:value};if(Number(extra)>0)item.extra_cost=Number(extra);return item});return options.length?{label,type:'select',default:options[0].value,options}:null}
async function load(){loading.value=true;try{[accounts.value,models.value]=await Promise.all([request.get('/provider-accounts'),request.get('/config/models')])}finally{loading.value=false}}
function openAccount(row){Object.assign(accountForm,emptyAccount(),row||{},{api_key:''});accountDialog.value=true}
async function saveAccount(){const body={...accountForm};delete body.id;if(accountForm.id)await request.put(`/provider-accounts/${accountForm.id}`,body);else await request.post('/provider-accounts',body);accountDialog.value=false;ElMessage.success('供应商账号已保存');await load()}
async function removeAccount(row){await ElMessageBox.confirm(`删除“${row.name}”？关联模型将变为未关联。`,'删除账号',{type:'warning'});await request.delete(`/provider-accounts/${row.id}`);await load()}
function openModel(row){const p=row.params_config||{};Object.assign(modelForm,{id:row.id,type:row.type,provider:row.provider,display_name:row.display_name,provider_account_id:row.provider_account_id,cost:row.cost,description:row.description,ratio:optionText(p.ratio),resolution:optionText(p.resolution),duration:optionText(p.duration),sound_enabled:Boolean(p.sound),sound_default:Boolean(p.sound?.default)});modelDialog.value=true}
async function saveModel(){const params={};const ratio=makeSelect('画面比例',modelForm.ratio),resolution=makeSelect('清晰度',modelForm.resolution);if(ratio)params.ratio=ratio;if(resolution)params.resolution=resolution;if(modelForm.type==='video'){const duration=makeSelect('时长',modelForm.duration);if(duration)params.duration=duration;if(modelForm.sound_enabled)params.sound={label:'生成声音',type:'switch',default:modelForm.sound_default}}await request.put(`/config/models/${modelForm.id}`,{display_name:modelForm.display_name,provider_account_id:modelForm.provider_account_id,cost:modelForm.cost,description:modelForm.description,params_config:params});modelDialog.value=false;ElMessage.success('模型能力已保存');await load()}
async function toggleModel(row){try{await request.put(`/config/models/${row.id}/status`,{is_active:row.is_active})}catch{row.is_active=!row.is_active}}
onMounted(load)
</script>

<style scoped>.accounts-page{padding:20px}.page-head,.section-head,.card-head,.card-actions{display:flex;align-items:center;justify-content:space-between}.page-head h2,.section-head h3{margin:0}.page-head p,.section-head span,.hint{color:#909399;font-size:13px}.account-grid{margin-top:20px}.account-grid .el-col{margin-bottom:16px}.card-actions{justify-content:flex-end;margin-top:14px}.model-section{margin-top:10px;background:#fff;padding:20px;border-radius:4px}.section-head{margin-bottom:16px}.full{width:100%}.hint{margin-left:12px}</style>
